[Logger]
enable = true
level = "debug"
full_logs = false
stream_handler = true
file_handler = true
file_path = "louie.log"
enable_datetime = false
datetime_format = "%Y-%m-%d %H:%M:%S"

[APISettings]
url = false
host = "localhost"
port = 8000
test_user = "f4b7b9e2-b26a-480a-ac43-0e085482390f"

[Whisper]
local = false # Para usar o Whisper localmente, defina como true, mas caso queira usar via API, defina como false
model = "whisper-1" # gpt-4o-transcribe, gpt-4o-mini-transcribe, whisper-1 

[Gemini]
model = "gemini-2.5-flash"
voce_name = "Kore"
assert_continue = true

[Database]
local = false
save_local = true
