[Logger]
enable = true
level = "debug"
stream_handler = true
file_handler = true
file_path = "louie.log"
enable_datetime = false
datetime_format = "%Y-%m-%d %H:%M:%S"

[APISettings]
url = false
host = "localhost"
port = 8000

[Whisper]
# Para usar o Whisper localmente, defina como true, mas caso queira usar via API, defina como false
local = false 
model = "whisper-1"