services:
  - type: web
    name: api
    runtime: docker
    dockerfilePath: docker/Dockerfile.api
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg && \
      pip install --no-cache-dir -r requirements/api.txt
    startCommand: |
      uvicorn api.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONPATH
        value: /app
    envFile: .env
    port: 8000

  - type: web
    name: frontend
    runtime: docker
    dockerfilePath: docker/Dockerfile.frontend
    buildCommand: |
      pip install --no-cache-dir -r requirements/st.txt
    startCommand: |
      streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: API_BASE_URL
        value: http://api:8000
    envFile: .env
    port: 8501

  - type: web
    name: nginx
    runtime: docker
    buildCommand: |
      apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*
    startCommand: |
      nginx -g 'daemon off;'
    envFile: .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
